//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPagamento
    {
        public int Id { get; set; }
        public bool Ativo { get; set; }
        public string Nome { get; set; }

        public override string ToString()
        {
            string str = $"{this.Nome}";
            return str;
        }
    }
}
