//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Morada
    {
        public int Id { get; set; }
        public string Rua { get; set; }
        public string Cidade { get; set; }
        public string Pais { get; set; }
        public string CodPostal { get; set; }


        public override string ToString()
        {
            string str = $"{this.Rua}, {this.CodPostal}, {this.Cidade}, {this.Pais}";
            return str;
        }
    }
}
