//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Pagamentos = new HashSet<Pagamento>();
            this.ItemMenus = new HashSet<ItemMenu>();
        }
    
        public int Id { get; set; }
        public int IdTrabalhador { get; set; }
        public int IdCliente { get; set; }
        public int IdRestaurante { get; set; }
        public int IdEstado { get; set; }
        public decimal ValorTotal { get; set; }
    
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamentos { get; set; }
        public virtual Pessoas_Cliente Pessoas_Cliente { get; set; }
        public virtual Restaurante Restaurante { get; set; }
        public virtual Pessoas_Trabalhador Pessoas_Trabalhador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMenu> ItemMenus { get; set; }
    }
}
