//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabalhador : Pessoa
    {
        public decimal Salario { get; set; }
        public string Posicao { get; set; }
        public int RestauranteId { get; set; }
    
        public virtual Restaurante Restaurante { get; set; }

        public override string ToString()
        {
            string str = $"{this.Nome}";
            return str;
        }
    }
}
